import React, { useEffect, useState } from 'react';
import Timer from './Timer';

const ContentLeft = () => {
	return (
		<div>
			<h1 className='text-2xl text-center font-poppins font-medium leading-1 sm:text-4xl md:text-left xl:text-5xl'>
				Bet and win an <br />
				exclusive Pokemon card <br />
				<span className='text-yellow-500 font-sanchez font-normal'>NFT</span>
			</h1>
			<div className='pt-4 mb-4'>
				<p className='text-center text-yellow-900'>
					Each Friday a lottery will be run among the participants. Every week
					the NFT will be unique.
				</p>
			</div>
			<div className='bg-stone-800 rounded-3xl shadow shadow-slate-50 p-4'>
				<p className='text-center text-1xl m-0 pt-0 lg:text-2xl'>
					Each card is randomly generated by an IA so each one is unique.
					Collect, play or sell these exclusive NFTs.
				</p>
			</div>
			{/* <div className='timer'>
				<Timer expiryTimestamp />
			</div> */}
		</div>
	);
};

export default ContentLeft;
