import React from 'react';

const ContentLeft = () => {
	return (
		<div>
			<h1 className='text-4xl'>
				Bet and win an <br />
				exclusive Pokemon card <br />
				<span className='text-yellow-500'>NFT</span>
			</h1>
			<div className='pt-4 mb-4'>
				<p className='text-yellow-900'>
					Each Friday a lottery will be run among the participants. Every week
					the NFT will be unique.
				</p>
			</div>
			<div className='bg-stone-800 rounded-3xl shadow shadow-slate-50 p-4'>
				<p className='pt-4 text-2xl m-0 p-0 pt-0'>
					Each card is randomly generated by an IA so each one is unique.
					Collect, play or sell these exclusive NFTs.
				</p>
			</div>
		</div>
	);
};

export default ContentLeft;
